package uk.ac.ed.inf;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 * This class includes 2 helper functions that used to send http request and get response.
 */
public class HttpUtils {
    /**
     * The client used to communicate with website.
     */
    public static final HttpClient client = HttpClient.newHttpClient();

    /**
     * initialize the http request by the input uri.
     * @param uri is the uri used to generate http request.
     * @return the http request generated by the uri.
     */
    public static HttpRequest setRequest(URI uri){
        HttpRequest request = HttpRequest.newBuilder().uri(uri).build();
        return request;
    }

    /**
     * send the http request and return the http response.
     * @param request the http request
     * @return the http response get by sending the http request.
     * @throws IOException IOException
     * @throws InterruptedException InterruptedException
     */
    public static HttpResponse<String> getResponse(HttpRequest request) throws IOException, InterruptedException {
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        return response;
    }
}
